### ISSUE TITLE
Add ability to visualize location providers

### ISSUE THREAD

**Issue by gdt** [OpenTracksApp/OSMDashboard#135]
This is a somewhat off-the-wall feature request.   I have been using MyLocation, which queries all the location providers and displays the values (lat/lon, error).   However, it doesn't show them on a map.   I suggested  this (https://github.com/mirfatif/MyLocation/issues/10) but the author doesn't want to add to the memory footprint.

So, I wonder if OSMDashboard could have a way to get an intent that's basically a set of tuples <color, lat, lon, error> and then draw circles, and be launched from some button in MyLocation that then sends the intents (until the backstack is popped, or ??).

I almost didn't file this issue, but I'm guessing you would think visualizing network location is interesting.   Thanks for listening.

**Comment by dennisguse** [comment]
We could use the location URI: https://developer.android.com/guide/components/intents-common.html#Maps and add additional parameters :)

**Comment by pstorch** [comment]
When I see it correctly the Maps intent is already implemented by MyLocation. You can select a provider in MyLocation and open a Map application with this one location. But I guess what @gdt wants is sending a list of coordinates (with additional properties like color and error) continuously (realtime) to a Map. Like SatStat has it build in. 
So something similar to what we have implemented between OpenTracks and OSMDashboard, but with single points instead of tracks. 
I think it would not be sooo complicated, but would be a separate API.

**Comment by pstorch** [comment]
Ah, you already asked SatStat as well: https://gitlab.com/mvglasow/satstat/-/issues/186

**Comment by gdt** [comment]
Sorry, wasn't trying to be sneaky.   I know it's a small world and the Android geonerds mostly know each other....

And yes, I definitely want to see them all at once with error circles, updated.  This is not "where am I", but "how are my location providers behaving".  Which is off-mission for OpenTracks, but also sort of a debugging aid, and perhaps a path to using network location when accuracy claims are ok, to reduce battery use, at some later time.

**Comment by pstorch** [comment]
Won't be part of OSMDashboard
